image: ubuntu

test_script:
- node --version
- sh: chmod +x script1.sh
- sh: chmod +x script2.sh
- nvm install 9
- node --version
- sh: yarn add lodash-node
- sh: node install lodash
- sh: ./script1.sh
#- sh: exit 1
- ls
- sh: ./script2.sh

build: off
